import { IDataComments } from '@/stores/interfaces/dataComments'

export const dataComments:IDataComments[] = [
    {
        id:1,
        comments:'',
        checked:false,
        textTooltip:'Вид: Новостройка / Дом / Вторичка. Тип: Студия, Однокомнатная, Двухкомнатная, Апартаменты.',
        label: 'Вид и Тип жилья',
    },
    {
        id:2,
        comments:'',
        checked:false,
        textTooltip:'Общая площадь, Жилая площадь, Площадь Кухни, Колличество комнат.',
        label: 'Общая площадь м²',
    },
    {
        id:3,
        comments:'',
        checked:false,
        textTooltip:'Автобус, Электричка, Метро, Автомобиль. Дистанция (кол-во минут) от недвижимости до транспорта.',
        label: 'Транспорт',
    },
    {
        id:4,
        comments:'',
        checked:false,
        textTooltip:'На каком этаже находится квартира. Первый и последний этаж не особо перспективный вариант.',
        label: 'Этаж',
    },
    {
        id:5,
        comments:'2',
        checked:false,
        textTooltip:'Аптеки, Больницы, Детские Сады, Магазины, ДЕЗ, Парки, Парковки, Спортивные площадки, ТРЦ.',
        label: 'Инфраструктура',
    },
    {
        id:6,
        comments:'',
        checked:false,
        textTooltip:'ТЭЦ, РЖД пути, Аэропорты, Заводы, Электрические проводные пути, Кладбище.',
        label: 'Экология',
    },
    {
        id:7,
        comments:'',
        checked:false,
        textTooltip:'Какая планировка у недвижимости. Есть ли отделка у застройщика и что в неё входит.',
        label: 'Планировки и Отделка',
    },
    {
        id:8,
        comments:'',
        checked:false,
        textTooltip:'В каком месяце и году начали строить и окончание постройки, дата вручение ключей и заселение.',
        label: 'Год и Месяц сдачи',
    },
    {
        id:9,
        comments:'',
        checked:false,
        textTooltip:'Какие акции, скидки у застройщика имеются и их условия.',
        label: 'Акции и Скидки',
    },
    {
        id:10,
        comments:'',
        checked:false,
        textTooltip:'Проверяем документы на недвижимость и смотреть как оформлять сделку. Аккредитован ли застройщик.',
        label: 'Юридическая проверка',
    },
    {
        id:11,
        comments:'',
        checked:false,
        textTooltip:'Можно поехать в нужный район и посмотреть физически местность.',
        label: 'Осмотр района',
    },
    {
        id:12,
        comments:'',
        checked:false,
        textTooltip:'Господдержка, Семейная ипотека, Ипотека для IT, Кредит под залог недвижимости и др.',
        label: 'Ипотечные программы',
    },
];
