import { IDataComments } from '@/stores/interfaces/dataComments'

export const dataComments:IDataComments[] = [
    {
        id:1,
        comments:'',
        checked:false,
        textTooltip:'Новостройка/Вторичка/Дом',
        label: 'Вид недвижимости',
    },
    {
        id:2,
        comments:'',
        checked:false,
        textTooltip:'Общая площадь недвижимости(жилая и не жилая)',
        label: 'м² в недвижимости',
    },
    {
        id:3,
        comments:'',
        checked:false,
        textTooltip:'Дистанция (кол-во минут) от транспорта до недвижимости и какой транспорт (Электричка, Автобус, Метро)',
        label: 'Доступность транспорта',
    },
    {
        id:4,
        comments:'',
        checked:false,
        textTooltip:'Аптеки, Больницы, Детский Сад, Магазины, ДЕЗ, Парк, Другие ЖК',
        label: 'Инфраструктура',
    },
    {
        id:5,
        comments:'2',
        checked:false,
        textTooltip:'Студия, Однокомнатная, Апартаменты, Двухкомнатная',
        label: 'Тип квартиры',
    },
    {
        id:6,
        comments:'',
        checked:false,
        textTooltip:'семейная, гос, айти и тд',
        label: 'Вид ипотеки',
    },
    {
        id:7,
        comments:'',
        checked:false,
        textTooltip:'Расположение заводов, Аэропортов, Кладбищь, ТЭЦ, Электрических путей',
        label: 'Экология',
    },
    {
        id:8,
        comments:'',
        checked:false,
        textTooltip:'TEXT-4',
        label: 'Аккредитован ластройщик',
    },
    {
        id:9,
        comments:'',
        checked:false,
        textTooltip:'TEXT-4',
        label: 'Планеровка',
    },
    {
        id:10,
        comments:'',
        checked:false,
        textTooltip:'TEXT-4',
        label: 'Отзывы о компании',
    },
    {
        id:11,
        comments:'',
        checked:false,
        textTooltip:'TEXT-4',
        label: 'Отзывы о компании',
    },
    {
        id:12,
        comments:'',
        checked:false,
        textTooltip:'TEXT-4',
        label: 'Отзывы о компании',
    },
];
